language: java

jdk:
    - openjdk11
    - openjdk8

install:
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

cache:
  directories:
  - $HOME/.m2
